# Linear Regression Model on the Weather Data

In [ ]:
#Pandas Makes reading files and input files quick

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import numpy as np
from sklearn.linear_model import LinearRegression
#from mixtend.evaluate import bias_viariance_decomp
import datetime

data =pd.read_csv('weatherHistory.csv')
data

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [7]:
data["Date"]=pd.to_datetime(data["Formatted Date"],utc=True)
data["Month"]= data["Date"].dt.month
data

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,Date,Month
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,2006-03-31 22:00:00+00:00,3
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,2006-03-31 23:00:00+00:00,3
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,2006-04-01 00:00:00+00:00,4
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,2006-04-01 01:00:00+00:00,4
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,2006-04-01 02:00:00+00:00,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.,2016-09-09 17:00:00+00:00,9
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.,2016-09-09 18:00:00+00:00,9
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.,2016-09-09 19:00:00+00:00,9
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.,2016-09-09 20:00:00+00:00,9
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.,2016-09-09 21:00:00+00:00,9

In [9]:
#deleting unnecessary columns
data=data.drop(['Formatted Date','Daily Summary','Pressure (millibars)','Loud Cover','Date'],axis=1)
data

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Month
0,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,3
1,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,3
2,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,4
3,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,4
4,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,4
...,...,...,...,...,...,...,...,...,...
96448,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,9
96449,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,9
96450,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,9
96451,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,9
96452,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,9

In [11]:
label_encoder=preprocessing.LabelEncoder()
data['Summary']=label_encoder.fit_transform(data['Summary'])
data['Summary'].unique()
data

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Month
0,19,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,3
1,19,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,3
2,17,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,4
3,19,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,4
4,17,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,4
...,...,...,...,...,...,...,...,...,...
96448,19,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,9
96449,19,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,9
96450,19,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,9
96451,19,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,9
96452,19,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,9

In [12]:
data['Precip Type']=data["Precip Type"].replace(['rain','snow'],[0,1])
data

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Month
0,19,0.0,9.472222,7.388889,0.89,14.1197,251.0,15.8263,3
1,19,0.0,9.355556,7.227778,0.86,14.2646,259.0,15.8263,3
2,17,0.0,9.377778,9.377778,0.89,3.9284,204.0,14.9569,4
3,19,0.0,8.288889,5.944444,0.83,14.1036,269.0,15.8263,4
4,17,0.0,8.755556,6.977778,0.83,11.0446,259.0,15.8263,4
...,...,...,...,...,...,...,...,...,...
96448,19,0.0,26.016667,26.016667,0.43,10.9963,31.0,16.1000,9
96449,19,0.0,24.583333,24.583333,0.48,10.0947,20.0,15.5526,9
96450,19,0.0,22.038889,22.038889,0.56,8.9838,30.0,16.1000,9
96451,19,0.0,21.522222,21.522222,0.60,10.5294,20.0,16.1000,9
96452,19,0.0,20.438889,20.438889,0.61,5.8765,39.0,15.5204,9

In [13]:
#checking for NaN values in data
data.isna().sum()

Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Month                         0
dtype: int64

In [14]:
#replacing NaN values with 0
data['Precip Type']=data['Precip Type'].replace(np.nan,0)
data.isna().sum()

Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Month                       0
dtype: int64

In [16]:
y=data['Apparent Temperature (C)']
data=data.drop('Apparent Temperature (C)',axis = 1)
print(data)

       Summary  Precip Type  Temperature (C)  Humidity  Wind Speed (km/h)  \
0           19          0.0         9.472222      0.89            14.1197
1           19          0.0         9.355556      0.86            14.2646
2           17          0.0         9.377778      0.89             3.9284
3           19          0.0         8.288889      0.83            14.1036
4           17          0.0         8.755556      0.83            11.0446
...        ...          ...              ...       ...                ...
96448       19          0.0        26.016667      0.43            10.9963
96449       19          0.0        24.583333      0.48            10.0947
96450       19          0.0        22.038889      0.56             8.9838
96451       19          0.0        21.522222      0.60            10.5294
96452       19          0.0        20.438889      0.61             5.8765

       Wind Bearing (degrees)  Visibility (km)  Month
0                       251.0          15.8263      3
1                       259.0          15.8263      3
2                       204.0          14.9569      4
3                       269.0          15.8263      4
4                       259.0          15.8263      4
...                       ...              ...    ...
96448                    31.0          16.1000      9
96449                    20.0          15.5526      9
96450                    30.0          16.1000      9
96451                    20.0          16.1000      9
96452                    39.0          15.5204      9

[96453 rows x 8 columns]

In [17]:
y

0         7.388889
1         7.227778
2         9.377778
3         5.944444
4         6.977778
           ...
96448    26.016667
96449    24.583333
96450    22.038889
96451    21.522222
96452    20.438889
Name: Apparent Temperature (C), Length: 96453, dtype: float64

In [19]:
x_train,x_test,y_train,y_test=train_test_split(data,y,test_size=0.2,random_state=0)

model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [20]:
pred=model.predict(x_test)

#finding variance using np
variance=np.var(pred)
variance

112.55774551091032

In [22]:
SSE=np.mean((np.mean(pred)-y)**2)
Bias=SSE-variance
Bias

1.8663327948125499